
services:
  web:
    build: .
    container_name: xor_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: xor_db
    restart: always
    environment:
      POSTGRES_DB: xor_db
      POSTGRES_USER: xor_user
      POSTGRES_PASSWORD: xor_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"   # optional (remove in production)

volumes:
  postgres_data:
    driver: local